### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by VulchiSarath** [powerbot15/image-compressor#1]
I installed npm image-compressor. 
my code is 

router.put('/person', function(req, res, next) {
    if (req.access === false) {
        res.send(401);
    }
    var encodedImage=""
    var form = new formidable.IncomingForm();

    form.parse(req, function(err, fields, files) {
         var fileSize = files.attachment.size;

       if(fileSize!=0){
            var filePath = files.attachment.path;
            var fileName = files.attachment.name;
            var fileType = files.attachment.type;
        
            encodedImage = imageBase64.local(filePath);
    
            var imageCompressor = new ImageCompressor;
            var compressorSettings = {
                toWidth : 100,
                toHeight : 100,
                mimeType : 'image/png',
                mode : 'strict',
                quality : 0.6,
                speed : 'low'
            };

            imageCompressor.run(filePath, compressorSettings, .proceedCompressedImage());
           
       }

function proceedCompressedImage(compressedsrc){
        console.log("---==-=-=-=-==-=-="+compressedsrc)
    }

How do i solve this issue ?

**Comment by powerbot15** [comment]
Sorry, but this library is intended for client side(browser) only. You can not use it on server-side

**Comment by VulchiSarath** [comment]
thanks @powerbot15. Any server-side library are there ?. Let me know if any
