### ISSUE TITLE
quality parameter doesn't work

### ISSUE THREAD

**Issue by rafian-git** [powerbot15/image-compressor#5]
quality parameter values between 0.1 to 0.9 doesn't seem to work(for mime type : PNG). Not even in the provided Demo. I've tried rendering images with parameters 0.1 and 0.9 , both of them returned images of same size. Please help  @powerbot15

**Comment by powerbot15** [comment]
Quality parameter works only for mime types `image/jpeg` and `image/webp`. It is described in the specification of canvas https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by rafian-git** [comment]
doesn't work even for your suggested  mime types. Not even in your demo. please check.
